name: AV Financial
favicon: null
layout_spectrum: 0
typography_spectrum: 0.13815
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b36c1b'
    - '#00ceff'
    - '#fffe00'
    - '#010100'
    - '#fffdf7'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
