name: AV Financial
favicon: null
layout_spectrum: 0.6652811351232231
typography_spectrum: 0.49023262970149517
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9594112816266716
  lightness: 0.18640195624902844
  saturation: 0.3796955880243331
  rhythmicContrast: 0.02590164542198181
purpose: []
